### PR TITLE
Enable website-wide Dark mode

### PR DESCRIPTION
**Pull request by git-pi-e**
- Created a homepage with TOC according to the pdf on slack
- Since the color scheme does not retain it's state on refresh, the color-toggler has been added to the header

Partially resolves: #3

### CODE REVIEW

**Comment by blackrosedragon2** [comment]
The toggle option looks great! One change is required for the landing page. The contents are subject to change, and that is why we cannot keep a static landing page. Could you create one that dynamically changes based on the contents of the ADL folders and subfolders?

**Comment by git-pi-e** [comment]
Yeah I'll try doing that

**Comment by git-pi-e** [comment]
> The toggle option looks great! One change is required for the landing page. The contents are subject to change, and that is why we cannot keep a static landing page. Could you create one that dynamically changes based on the contents of the ADL folders and subfolders? The implementation can be somewhat like the navigation of the website.

Is the jekyll code available for the aima available/open source? I've been trying to do it, no success so far,

**Comment by git-pi-e** [comment]
Website wide dark mode applied.

**Pull request merged**
